.\" Manpage for run
.TH RUN 1 "2025-09-26" "v1.0.0" "Basic abstraction to facilitate Linux terminal coding"
.SH NAME
run \- basic abstraction to compile, execute and interpret multiple programming languages

.SH SYNOPSIS
.B run
[\fIOPTIONS\fR] <\fIfile_or_java_directory\fR>

.SH DESCRIPTION
\fBRun\fR is a Bash script that acts as a basic abstraction layer for compiling, executing, and interpreting source files across multiple programming languages. It simplifies Linux terminal workflows by unifying commands and automatically detecting common project structures.

.SH OPTIONS

.TP
.B <file>
Compile and execute (default behavior).

.TP
.B -c <file>
Compile only.

.TP
.B -e <file>
Execute only (already compiled).

.TP
.B -i <file>
Interpret only (for script languages).

.SH JAVA PROJECT OPTIONS

.TP
.B --java <dir>
Compile and run Java project.

.TP
.B -c --java <dir>
Compile Java project only.

.TP
.B -e --java <dir>
Run compiled Java project.

.TP
.B -i --java <dir>
Run classes directly (no JAR).

.SH OTHER OPTIONS

.TP
.B --version
Show script version.

.TP
.B --help
Show this help message.

.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B 1
General error (compilation failed, file not found, etc.).
.TP
.B 2
Usage error (invalid options or arguments).

.SH AUTHOR
Eduardo Hoffmann do Carmo Silva <ehcs.business@gmail.com>


